import {
  skillSearchDuckduckgo,
  skillSearchWikipedia,
  skillSearchGithub,
  skillSearchGoogle,
  skillSearchGoogletranslate,
  skillSearchGoogleimages,
  skillSearchGooglemaps,
  skillSearchYoutube,
  skillSearchMdn,
  skillSearchNpm,
  skillSearchTwitter,
  skillSearchStackoverflow,
  skillSearchWolfram,
  skills,
} from './saihubot-skill-search.js';

export {
  skillSearchDuckduckgo,
  skillSearchWikipedia,
  skillSearchGithub,
  skillSearchGoogle,
  skillSearchGoogletranslate,
  skillSearchGoogleimages,
  skillSearchGooglemaps,
  skillSearchYoutube,
  skillSearchMdn,
  skillSearchNpm,
  skillSearchTwitter,
  skillSearchStackoverflow,
  skillSearchWolfram,
  skills,
};
